import Image from "next/image";
import Link from "next/link";
import { CalendarCheck, Camera, CheckCircle2, MapPin, Phone, ShieldCheck, Smartphone, Video } from "lucide-react";
import type { ServiceContent } from "../../lib/content/services";
import { ContactForm } from "../forms/ContactForm";
import { SiteFooter } from "../layout/SiteFooter";
import { SiteHeader } from "../layout/SiteHeader";

const phoneDisplay = "03 9872 2722";
const bookingUrl = "https://calendly.com/asapautoelectrics/auto-electrical-repair";
const included = ["4K Ultra HD front dash camera", "1080P rear dash camera", "Front and rear simultaneous recording", "Parking mode with impact detection", "Wi-Fi smartphone connectivity", "Hardwire installation kit", "32GB TF memory card included", "Support for TF cards up to 128GB", "Professional concealed wiring", "Installation by an auto electrician", "Testing and setup before vehicle handover"];
type DashCamFeature = { title: string; icon: typeof Camera; copy: string; image?: string; imageAlt?: string };
const features: DashCamFeature[] = [
  { title: "4K Ultra HD Front Camera", icon: Camera, copy: "Records at 3840 × 2160 resolution at 30FPS. The higher resolution helps capture road detail clearly, including number plates and surrounding traffic where conditions allow.", image: "/reference/images/2026/dash-cam-rear.jpg", imageAlt: "4K front dash cam mounted near rear view mirror" },
  { title: "1080P Rear Camera", icon: Video, copy: "Provides high-definition rear coverage while recording simultaneously with the front camera.", image: "/images/services/dash-cam/dash-cam-rear.jpg", imageAlt: "1080P rear dash cam professionally installed" },
  { title: "Dual Channel Recording", icon: Video, copy: "Front and rear cameras record at the same time to provide more complete coverage around the vehicle." },
  { title: "143° Wide-Angle Coverage", icon: Camera, copy: "Both cameras use 143° wide-angle lenses. The broad field of view helps reduce blind areas in recorded footage." },
  { title: "Compact & Discreet Design", icon: Camera, copy: "The screenless front camera mounts neatly behind or near the rear-view mirror for an unobtrusive installation, minimal obstruction to driver vision and a clean OEM-style appearance." },
  { title: "Continuous Loop Recording", icon: Video, copy: "The camera records continuously and automatically overwrites the oldest unlocked footage when the memory card becomes full." },
  { title: "Parking Mode with Impact Detection", icon: ShieldCheck, copy: "When properly hardwired, compatible parking mode can monitor the parked vehicle and record when an impact is detected. Operation depends on available battery voltage and the system’s voltage-protection settings." },
  { title: "Automatic Operation", icon: ShieldCheck, copy: "The system powers on when the vehicle starts and transitions according to the installed hardwire configuration, making it practical for hands-free everyday use." },
  { title: "Wi-Fi Connectivity", icon: Smartphone, copy: "Connect a compatible smartphone to view recordings, download footage, save clips and share recordings. Functions depend on the supplied camera app and smartphone compatibility.", image: "/reference/images/2026/dash-cam-phone.jpg", imageAlt: "Dash cam Wi-Fi connection to smartphone" },
  { title: "Memory Card Included", icon: Camera, copy: "A 32GB TF card is supplied, with support for cards up to 128GB. Higher-capacity cards retain more footage before loop recording overwrites older unlocked files." }
];
const installation = ["Concealed wiring where practical", "Correct ignition-switched supply", "Constant battery supply for parking mode where required", "Appropriate fuse protection", "Correct earth connection", "Suitable circuit selection", "Battery-voltage protection", "Careful routing around airbags and trim", "Clean professional finish", "System operation tested before handover"];
const whyAsap = ["Installed by experienced auto electricians", "Professional hardwired installation", "Front and rear camera package supplied", "Parking-mode wiring included where suitable", "Clean concealed wiring", "Electrical system tested before connection", "Ringwood workshop", "Local established auto electrical business"];
const vehicles = ["Passenger vehicles", "SUVs", "4WDs", "Utes", "Light commercial vehicles"];

const ButtonPair = () => <div className="flex flex-col gap-3 sm:flex-row"><a href={bookingUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-asap-cyan px-6 font-black text-slate-950 transition hover:bg-asap-purple hover:text-white"><CalendarCheck size={20} aria-hidden />Book Dash Cam Installation</a><a href="tel:0398722722" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border-2 border-asap-purple px-6 font-black text-asap-purple transition hover:bg-asap-purple hover:text-white"><Phone size={20} aria-hidden />Call {phoneDisplay}</a></div>;
const Checks = ({ items }: { items: string[] }) => <ul className="grid gap-3 sm:grid-cols-2">{items.map(item => <li key={item} className="flex gap-2 font-bold"><CheckCircle2 className="mt-0.5 shrink-0 text-asap-cyan" size={20} aria-hidden />{item}</li>)}</ul>;

export function DashCamPage({ service }: { service: ServiceContent }) {
  const serviceSchema = { "@context": "https://schema.org", "@type": "Service", name: "Dash Cam Supply & Installation", description: service.metaDescription, url: "https://www.asapauto.com.au/services/dash-cam-installation", provider: { "@type": "AutoRepair", name: "ASAP Auto Electrics", telephone: "+61398722722", address: { "@type": "PostalAddress", streetAddress: "Unit 3/3 Oban Rd", addressLocality: "Ringwood", addressRegion: "VIC", postalCode: "3134", addressCountry: "AU" } }, areaServed: "Melbourne eastern and outer-eastern suburbs" };
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: service.faqs.map(faq => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://www.asapauto.com.au/" }, { "@type": "ListItem", position: 2, name: "Services", item: "https://www.asapauto.com.au/#services" }, { "@type": "ListItem", position: 3, name: "Dash Cam Installation", item: "https://www.asapauto.com.au/services/dash-cam-installation" }] };
  return <main className="min-h-screen bg-white text-slate-950"><SiteHeader />
    <section className="relative overflow-hidden bg-slate-50"><div className="absolute inset-x-0 top-0 h-2 bg-[linear-gradient(90deg,#ED2E38,#00A6D6,#2905A1)]" /><div className="mx-auto max-w-7xl px-4 pb-12 pt-7 sm:px-6 lg:px-8 lg:pb-16"><nav aria-label="Breadcrumb" className="mb-6 text-sm font-bold text-slate-600"><ol className="flex flex-wrap gap-2"><li><Link href="/">Home</Link></li><li>/</li><li><Link href="/#services">Services</Link></li><li>/</li><li className="text-slate-950">Dash Cam Installation</li></ol></nav><div className="grid items-center gap-10 lg:grid-cols-[1fr_0.9fr]"><div><p className="text-sm font-black uppercase tracking-wide text-asap-red">4K Front + 1080P Rear · Ringwood Workshop</p><h1 className="mt-3 font-display text-5xl font-black leading-[0.98] sm:text-6xl">Dash Cam Supply &amp; Installation</h1><p className="mt-5 text-3xl font-black text-asap-purple">From $699 Supplied &amp; Fitted</p><p className="reading-text mt-5 max-w-2xl">Protect your vehicle with a professionally installed front and rear dash cam system.</p><p className="reading-text mt-3 max-w-2xl">Our package includes a 4K Ultra HD front camera, 1080P rear camera, parking mode, Wi-Fi connectivity and hardwire kit, professionally installed by an auto electrician at our Ringwood workshop.</p><div className="mt-7"><ButtonPair /></div><p className="mt-4 max-w-xl text-sm font-semibold leading-5 text-slate-600">From $699 supplied and fitted. Final price may vary depending on vehicle and installation requirements.</p><p className="mt-4 flex gap-2 text-sm font-bold text-asap-purple"><MapPin size={18} className="shrink-0 text-asap-cyan" aria-hidden />Workshop-based installation in Ringwood. We do not provide mobile installation.</p></div><div className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-2xl"><Image src={service.heroImage} alt={service.heroImageAlt} width={1200} height={760} priority className="aspect-[4/3] w-full object-cover" /></div></div></div></section>
    <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-[0.7fr_1.3fr]"><div><h2 className="text-4xl font-black">What&apos;s Included</h2><p className="mt-5 text-2xl font-black text-asap-purple">Supplied &amp; professionally installed from $699</p></div><Checks items={included} /></div></div></section>
    <section className="bg-slate-50 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-4xl font-black">Dash Cam Package Features</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(({title, icon: Icon, copy, image, imageAlt}) => <article key={title} className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm">{image && imageAlt && <Image src={image} alt={imageAlt} width={1456} height={1092} sizes="(max-width: 767px) 100vw, (max-width: 1023px) 50vw, 33vw" className="aspect-[4/3] w-full object-cover" />}<div className="p-6"><Icon className="text-asap-purple" size={28} aria-hidden /><h3 className="mt-4 text-xl font-black">{title}</h3><p className="reading-text mt-3">{copy}</p></div></article>)}</div></div></section>
    <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="text-sm font-black uppercase text-asap-red">Correct installation matters</p><h2 className="mt-3 text-4xl font-black">Professionally Hardwired by an Auto Electrician</h2><p className="reading-text mt-5">Dash cams are electrical accessories. Correct installation matters, particularly when parking mode requires a permanent battery supply.</p><p className="reading-text mt-4">The camera is connected to the vehicle electrical system instead of relying on loose cigarette-lighter or USB power leads. Modern vehicles can have sensitive electrical systems, so circuits are tested before connection.</p><div className="mt-7 overflow-hidden rounded-lg border border-slate-200 bg-slate-50 shadow-sm"><Image src="/images/services/dash-cam/dash-cam-install.jpg" alt="Auto electrician professionally hardwiring a dash cam" width={1456} height={1092} sizes="(max-width: 1023px) 100vw, 50vw" className="aspect-[4/3] w-full object-cover" /></div></div><div className="lg:pt-12"><Checks items={installation} /></div></div></section>
    <section className="bg-asap-purple px-4 py-16 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-4xl font-black">Why Choose ASAP for Dash Cam Installation?</h2><div className="mt-8 [&_li]:text-white"><Checks items={whyAsap} /></div></div></section>
    <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-2"><div><h2 className="text-4xl font-black">Suitable for Most Cars, SUVs, 4WDs and Utes</h2><p className="reading-text mt-5">Installation requirements vary between vehicles. Some vehicles may require additional time, components or specialised electrical integration.</p></div><Checks items={vehicles} /></div></section>
    <section className="bg-slate-50 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl rounded-lg bg-white p-7 shadow-xl ring-1 ring-slate-200 sm:p-10"><p className="text-sm font-black uppercase text-asap-red">Complete front and rear package</p><h2 className="mt-3 text-4xl font-black">Dash Cam Supply &amp; Installation</h2><p className="mt-5 text-3xl font-black text-asap-purple">From $699 Supplied &amp; Fitted</p><div className="mt-7"><Checks items={["4K front camera", "1080P rear camera", "Hardwire kit", "32GB memory card", "Front and rear installation", "Parking-mode wiring where suitable", "Setup and testing"]} /></div><p className="reading-text mt-7">Final pricing depends on the vehicle and installation requirements. Contact ASAP Auto Electrics for confirmation before booking.</p><div className="mt-7"><ButtonPair /></div></div></section>
    <section id="faqs" className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-4xl font-black">Frequently asked questions</h2><div className="mt-8 grid gap-3">{service.faqs.map(faq => <details key={faq.question} className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer text-lg font-black">{faq.question}</summary><p className="reading-text mt-4 max-w-4xl">{faq.answer}</p></details>)}</div></div></section>
    <section className="bg-slate-100 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-black">Related auto electrical services</h2><div className="mt-6 flex flex-wrap gap-3"><Link href="/services/auto-electrical-diagnostics" className="rounded-full bg-white px-5 py-3 font-black shadow-sm ring-1 ring-slate-200">Auto Electrical Diagnostics</Link><Link href="/services/battery-charging-system" className="rounded-full bg-white px-5 py-3 font-black shadow-sm ring-1 ring-slate-200">Battery &amp; Charging System</Link></div></div></section>
    <section id="contact" className="px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-sm font-black uppercase text-asap-red">Ringwood workshop</p><h2 className="mt-3 text-4xl font-black">Book Dash Cam Installation</h2><p className="reading-text mt-5">Tell us your vehicle details so we can confirm installation requirements and pricing. Installation is completed at our Ringwood workshop; we do not provide mobile service.</p><div className="mt-7"><ButtonPair /></div></div><ContactForm sourcePage="/services/dash-cam-installation" serviceName="Dash Cam Installation" heading="Tell us about your vehicle" submitLabel="Send Dash Cam Enquiry" /></div></section>
    <SiteFooter /><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(serviceSchema).replace(/</g, "\\u003c")}} /><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(faqSchema).replace(/</g, "\\u003c")}} /><script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(breadcrumbSchema).replace(/</g, "\\u003c")}} />
  </main>;
}
