import { CheckCircle2 } from "lucide-react";
import type { ServiceContent } from "../../lib/content/services";

const Section = ({ children, grey = false, id }: { children: React.ReactNode; grey?: boolean; id?: string }) => <section id={id} className={`${grey ? "bg-slate-50" : "bg-white"} px-4 py-16 sm:px-6 lg:px-8`}><div className="mx-auto max-w-7xl">{children}</div></section>;

export function ServiceSymptoms({ service }: { service: ServiceContent }) { return <Section><h2 className="max-w-3xl text-4xl font-black">{service.symptomsHeading}</h2><ul className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{service.symptoms.map(x => <li key={x} className="flex gap-3 rounded-lg border border-slate-200 bg-white p-4 font-bold shadow-sm"><CheckCircle2 className="shrink-0 text-asap-cyan" aria-hidden />{x}</li>)}</ul></Section>; }
export function ServiceOverview({ service }: { service: ServiceContent }) { return <Section grey><div className="grid gap-8 lg:grid-cols-[0.75fr_1.25fr]"><h2 className="text-4xl font-black">{service.overviewHeading}</h2><div className="max-w-3xl space-y-5">{service.overviewParagraphs.map(x => <p className="reading-text" key={x}>{x}</p>)}</div></div></Section>; }
export function ServiceProcess({ service }: { service: ServiceContent }) { return <Section><h2 className="text-4xl font-black">{service.processHeading}</h2><ol className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{service.processSteps.map((x,i) => <li key={x.title} className="rounded-lg border border-slate-200 p-5 shadow-sm"><span className="text-sm font-black text-asap-red">STEP {i+1}</span><h3 className="mt-2 text-xl font-black">{x.title}</h3><p className="reading-text mt-2">{x.description}</p></li>)}</ol></Section>; }
export function ServiceFeatures({ service }: { service: ServiceContent }) { return <Section grey><div className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-4xl font-black">{service.featuresHeading}</h2><ul className="mt-6 grid gap-3 sm:grid-cols-2">{service.features.map(x => <li key={x} className="flex gap-2 font-bold"><CheckCircle2 className="shrink-0 text-asap-cyan" size={20} aria-hidden />{x}</li>)}</ul></div><div className="rounded-lg bg-asap-purple p-8 text-white sm:p-10"><h2 className="text-3xl font-black">Vehicles we diagnose</h2><ul className="mt-7 grid gap-4 sm:grid-cols-2">{service.vehicles.map(x => <li key={x} className="flex gap-2 font-bold"><CheckCircle2 className="shrink-0 text-asap-cyan" size={20} aria-hidden />{x}</li>)}</ul><p className="reading-text mt-8 text-white/80">Actual diagnostic capability depends on the vehicle and system type. Contact us with your vehicle details before booking if you are unsure.</p></div></div></Section>; }
export function ServiceFAQ({ service }: { service: ServiceContent }) { return <Section id="faqs"><h2 className="text-4xl font-black">Frequently asked questions</h2><div className="mt-8 grid gap-3">{service.faqs.map(x => <details key={x.question} className="group rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><summary className="cursor-pointer text-lg font-black">{x.question}</summary><p className="reading-text mt-4 max-w-4xl">{x.answer}</p></details>)}</div></Section>; }
